### ISSUE TITLE
Nativescript-Vue imageModule.initialize() not working

### ISSUE THREAD

**Issue by Nais0ne** [Akylas/nativescript-image#11]
Tried to replicate https://github.com/Akylas/nativescript-image/blob/master/demo-vue/app/app.js but at imageModule.initialize() it tells me while compiling "Cannot read property 'initialize' of undefined"
imported imageModule like in the example with `import * as imageModule from 'nativescript-image';`
When i log the imageModule before the initialize i get an object with just a few string key-values.
if i do `console.log(imageModule === undefined);` it logs false, so it should be defined, despite telling me it is not.

you can find the error log here: https://pastebin.com/K4kUdYiJ

I don't think it matters here, but i'm developing on android.

am I doing something wrong here?

**Comment by farfromrefug** [comment]
There must be something wrong with your setup.  Hard to say without your full setup:
- using angular/vue ... ?
- using typescript? if so what's your tsconfig
- what does your webpack file look like

**Comment by Nais0ne** [comment]
Like the title says, I'm using vue. Not using typescript and here is my webpack.config.js: https://pastebin.com/qH8JdnEP

**Comment by farfromrefug** [comment]
@Nais0ne  you have a babelrc  ? it should work as it is. you can look at the generated js in the platforms folder to see what s  happening

**Comment by Nais0ne** [comment]
I'm so sorry guys, deleting the platforms folder fixed it for me, sorry for bothering you :/
