### ISSUE TITLE
Support for Base64 on placeholderImageUri and failureImageUi

### ISSUE THREAD

**Issue by asiedusamuel** [Akylas/nativescript-image#14]
Is there any way to set a base64 encoded image for placeholder and failure image uri. I am trying to set an image generated from user initial in base64 as placeholders and failure images.

**Comment by farfromrefug** [comment]
@asiedusamuel not right now. Will add it

**Comment by asiedusamuel** [comment]
Have upgraded to v2.2.3 but still not working. 
I have used LoadFromBase64 on placeholderImageUrl and failureImageUri but still cant get it to work.
Base64 Images only works for src.

**Comment by farfromrefug** [comment]
@asiedusamuel just tried and it works here for both platforms. I created an example here:
https://github.com/Akylas/nativescript-image/blob/master/demo/app/examples/base64-fragment.ts

Tell me if you still dont get it to work.

**Comment by asiedusamuel** [comment]
Thanks man. Looks like there are multiple examples there which will help
