### ISSUE TITLE
Console.log in image.ios.js file

### ISSUE THREAD

**Issue by EvenHus** [Akylas/nativescript-image#15]
Hi, 
This is not an problem, but i don't understand why it is necessary to have a console.log in the image.ios.js file. I have a feed in my application that loads a lot of images. And i really love your plugin, but the logs are a bit annoying. Is it possible to get the log as an option in future builds?

**Comment by farfromrefug** [comment]
@EvenHus It is not necessary :D Will remove it right away!

**Comment by farfromrefug** [comment]
@EvenHus the fix have been released in 2.2.4

**Comment by EvenHus** [comment]
Perfect, thank you for a quick answer.
