### ISSUE TITLE
Touch events ignored when animating

### ISSUE THREAD

**Issue by bakerac4** [Akylas/nativescript-image#18]
When items are animated in, if you try and touch an item (i.e scroll or tap) its ignored until the animation is completed.

According to this https://github.com/SDWebImage/SDWebImage/pull/2315#event-1609374779 it should be working?

**Comment by farfromrefug** [comment]
@bakerac4 please :
* give informations about the version, platform ... (even though i know it is iOS)
* post a simple example project.
Thanks
