### ISSUE TITLE
Failed to build on IOS

### ISSUE THREAD

**Issue by anaszgh** [Akylas/nativescript-image#19]
Platform: IOS
CLI Version: 5.4.2
Core Modules Version: 5.2.0

Issue: 

I'm using another plugin called Photo Zoom, the plugin uses SDWebImage Pod version 4.0
where this plugin uses version 5.0.0-beta3 of the same pod.

Is there a ways to make the build running by using both of the plugins?

**Comment by farfromrefug** [comment]
@anaszgh not sure that possible yet. Please ask this on {N} repo
