### ISSUE TITLE
No readme in the published package at npm

### ISSUE THREAD

**Issue by VladimirAmiorkov** [Akylas/nativescript-image#5]
Latest version [in npm](https://www.npmjs.com/package/nativescript-image ) does not have any readme. It will be useful to include a [README.MD](https://github.com/Akylas/nativescript-image/blob/master/README.md) in the package in the future versions.

**Comment by farfromrefug** [comment]
This is fixed now. I will let you confirm and close this issue.
THakns

**Comment by VladimirAmiorkov** [comment]
@farfromrefug =Yes it is, cheers. Closing this issue.
